//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekreatnine_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nekreatnina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nekreatnina()
        {
            this.SlikeNekreatnina = new HashSet<SlikeNekreatnina>();
            this.StanApartman = new HashSet<StanApartman>();
            this.Favorit = new HashSet<Favorit>();
            this.Izdavac = new HashSet<Izdavac>();
        }
    
        public int NekreatninaId { get; set; }
        public int VrstaId { get; set; }
        public int LokacijaId { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public Nullable<int> Velicina { get; set; }
        public string Opis { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
        public virtual VrstaNekreatnine VrstaNekreatnine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlikeNekreatnina> SlikeNekreatnina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StanApartman> StanApartman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorit> Favorit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izdavac> Izdavac { get; set; }
    }
}
