//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekreatnine_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poruka
    {
        public int PorukaId { get; set; }
        public int KorisnikId { get; set; }
        public int IzdavacId { get; set; }
        public string Naslov { get; set; }
        public string Poruka1 { get; set; }
    
        public virtual Izdavac Izdavac { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
