//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekreatnine_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlikeNekreatnina
    {
        public byte[] Slika { get; set; }
        public int NekreatninaId { get; set; }
        public int SlikeNekreatninaId { get; set; }
    
        public virtual Nekreatnina Nekreatnina { get; set; }
    }
}
