//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekreatnine_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanApartman
    {
        public int StanId { get; set; }
        public int NekreatninaId { get; set; }
        public Nullable<int> CijenaKvadrata { get; set; }
        public Nullable<bool> Uknjizeno { get; set; }
        public string Opremljenost { get; set; }
        public Nullable<bool> Grijanje { get; set; }
        public Nullable<bool> Lift { get; set; }
        public Nullable<bool> Balkon { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<bool> Plin { get; set; }
        public Nullable<bool> KablovksaTv { get; set; }
    
        public virtual Nekreatnina Nekreatnina { get; set; }
    }
}
